### ISSUE TITLE
CFException does not seem to be auto-loaded by composer.

### ISSUE THREAD

**Issue by echoesactiii** [okwinza/CloudFlare-API#6]
Using composer 1.0-dev (40c14709f79f9d7ea35ac969cfbd7f41beb525bb), requiring this project with composer and loading the composer autoloader, an application will fail when it reaches a CFException for any reason:

`Fatal error: Class 'okw\CF\Exception\CFException' not found in ./vendor/okwinza/cloudflare-api/okw/CF/CF.php on line 167`

If then I add:
`require "vendor/okwinza/cloudflare-api/okw/CF/CFException.php";`
to the top of my PHP file, above:
`require_once 'vendor/autoload.php';`
it works as expected.

**Comment by skylord123** [comment]
I'm having the same issue. I am using this with Symfony 2.8 and looks like the `CFException` is not being loaded.

Is there plans to get this fixed any time soon?

**Comment by ManneW** [comment]
Hi!

I think this is due to an old version being the last stable release in Packagist.
- At the `1.0.2` tag, there is no `CF/Exception` folder (see [this tree](https://github.com/okwinza/CloudFlare-API/tree/1.0.2/okw/CF))
- At the last commit on master, there is a `CF/Exception` folder (see [this tree](https://github.com/okwinza/CloudFlare-API/tree/c3b3ace495c3ab7fd335ec56607aa6fa72868d4a/okw/CF))

I believe the missing folder is the reason why Composer fails to autoload the `CFException` class, since this is assumed to be located in that folder.

I guess the best way to solve it would be for @okwinza to create tag a new release, but in the meantime I think one could solve it by changing the composer requirement for the package to something along these lines:

```
"okwinza/cloudflare-api": "dev-master"
```

Or perhaps this if you want to make sure that it's the currently latest commit to the master branch that is being installed:

```
"okwinza/cloudflare-api": "dev-master#c3b3ace495c3ab7fd335ec56607aa6fa72868d4a"
```

**Comment by okwinza** [comment]
Much thanks @ManneW for digging into this issue and sorry it took so long. 

Sadly, i've barely had any time for open source stuff lately but it is going to change very soon. I'm looking at the code right now and there are many things i'd change(abstract away from curl for example), so expect major version bump in the near future.

As for now, i pushed new tag and updated the package on packagist just in case.
Please, check back if the issue is still relevant.

Cheers!
